# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rballard/work/workspace/PyCronScheduler/src/UIs/JobEditDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_JobEditDialog(object):
    def setupUi(self, JobEditDialog):
        JobEditDialog.setObjectName(_fromUtf8("JobEditDialog"))
        JobEditDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        JobEditDialog.resize(516, 411)
        JobEditDialog.setModal(True)
        self.verticalWidget = QtGui.QWidget(JobEditDialog)
        self.verticalWidget.setGeometry(QtCore.QRect(0, 0, 511, 371))
        self.verticalWidget.setObjectName(_fromUtf8("verticalWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.verticalWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.comment_lineEdit = QtGui.QLineEdit(self.verticalWidget)
        self.comment_lineEdit.setObjectName(_fromUtf8("comment_lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comment_lineEdit)
        self.label_2 = QtGui.QLabel(self.verticalWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.command_lineEdit = QtGui.QLineEdit(self.verticalWidget)
        self.command_lineEdit.setObjectName(_fromUtf8("command_lineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.command_lineEdit)
        self.enable_job_checkBox = QtGui.QCheckBox(self.verticalWidget)
        self.enable_job_checkBox.setCheckable(True)
        self.enable_job_checkBox.setChecked(False)
        self.enable_job_checkBox.setTristate(False)
        self.enable_job_checkBox.setObjectName(_fromUtf8("enable_job_checkBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.enable_job_checkBox)
        self.label_4 = QtGui.QLabel(self.verticalWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtGui.QLabel(self.verticalWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.min_lineEdit = QtGui.QLineEdit(self.verticalWidget)
        self.min_lineEdit.setObjectName(_fromUtf8("min_lineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.min_lineEdit)
        self.label_5 = QtGui.QLabel(self.verticalWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.groupBox = QtGui.QGroupBox(self.verticalWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.day_checkBox_1 = QtGui.QCheckBox(self.groupBox)
        self.day_checkBox_1.setGeometry(QtCore.QRect(10, 0, 38, 22))
        self.day_checkBox_1.setObjectName(_fromUtf8("day_checkBox_1"))
        self.day_checkBox_2 = QtGui.QCheckBox(self.groupBox)
        self.day_checkBox_2.setGeometry(QtCore.QRect(50, 0, 38, 22))
        self.day_checkBox_2.setObjectName(_fromUtf8("day_checkBox_2"))
        self.day_checkBox_3 = QtGui.QCheckBox(self.groupBox)
        self.day_checkBox_3.setGeometry(QtCore.QRect(90, 0, 38, 22))
        self.day_checkBox_3.setObjectName(_fromUtf8("day_checkBox_3"))
        self.day_checkBox_4 = QtGui.QCheckBox(self.groupBox)
        self.day_checkBox_4.setGeometry(QtCore.QRect(130, 0, 39, 22))
        self.day_checkBox_4.setObjectName(_fromUtf8("day_checkBox_4"))
        self.day_checkBox_5 = QtGui.QCheckBox(self.groupBox)
        self.day_checkBox_5.setGeometry(QtCore.QRect(170, 0, 38, 22))
        self.day_checkBox_5.setObjectName(_fromUtf8("day_checkBox_5"))
        self.day_checkBox_6 = QtGui.QCheckBox(self.groupBox)
        self.day_checkBox_6.setGeometry(QtCore.QRect(210, 0, 38, 22))
        self.day_checkBox_6.setObjectName(_fromUtf8("day_checkBox_6"))
        self.day_checkBox_7 = QtGui.QCheckBox(self.groupBox)
        self.day_checkBox_7.setGeometry(QtCore.QRect(250, 0, 38, 22))
        self.day_checkBox_7.setObjectName(_fromUtf8("day_checkBox_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.groupBox)
        self.label_6 = QtGui.QLabel(self.verticalWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_6)
        self.groupBox_2 = QtGui.QGroupBox(self.verticalWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sun_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.sun_checkBox.setObjectName(_fromUtf8("sun_checkBox"))
        self.horizontalLayout_3.addWidget(self.sun_checkBox)
        self.mon_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.mon_checkBox.setObjectName(_fromUtf8("mon_checkBox"))
        self.horizontalLayout_3.addWidget(self.mon_checkBox)
        self.tue_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.tue_checkBox.setObjectName(_fromUtf8("tue_checkBox"))
        self.horizontalLayout_3.addWidget(self.tue_checkBox)
        self.wed_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.wed_checkBox.setObjectName(_fromUtf8("wed_checkBox"))
        self.horizontalLayout_3.addWidget(self.wed_checkBox)
        self.thr_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.thr_checkBox.setObjectName(_fromUtf8("thr_checkBox"))
        self.horizontalLayout_3.addWidget(self.thr_checkBox)
        self.fri_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.fri_checkBox.setObjectName(_fromUtf8("fri_checkBox"))
        self.horizontalLayout_3.addWidget(self.fri_checkBox)
        self.sat_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.sat_checkBox.setObjectName(_fromUtf8("sat_checkBox"))
        self.horizontalLayout_3.addWidget(self.sat_checkBox)
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.groupBox_2)
        self.horizontalGroupBox = QtGui.QGroupBox(self.verticalWidget)
        self.horizontalGroupBox.setObjectName(_fromUtf8("horizontalGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.jan_checkBox = QtGui.QCheckBox(self.horizontalGroupBox)
        self.jan_checkBox.setObjectName(_fromUtf8("jan_checkBox"))
        self.horizontalLayout_2.addWidget(self.jan_checkBox)
        self.feb_checkBox = QtGui.QCheckBox(self.horizontalGroupBox)
        self.feb_checkBox.setObjectName(_fromUtf8("feb_checkBox"))
        self.horizontalLayout_2.addWidget(self.feb_checkBox)
        self.mar_checkBox = QtGui.QCheckBox(self.horizontalGroupBox)
        self.mar_checkBox.setObjectName(_fromUtf8("mar_checkBox"))
        self.horizontalLayout_2.addWidget(self.mar_checkBox)
        self.apr_checkBox = QtGui.QCheckBox(self.horizontalGroupBox)
        self.apr_checkBox.setObjectName(_fromUtf8("apr_checkBox"))
        self.horizontalLayout_2.addWidget(self.apr_checkBox)
        self.may_checkBox = QtGui.QCheckBox(self.horizontalGroupBox)
        self.may_checkBox.setObjectName(_fromUtf8("may_checkBox"))
        self.horizontalLayout_2.addWidget(self.may_checkBox)
        self.jun_checkBox = QtGui.QCheckBox(self.horizontalGroupBox)
        self.jun_checkBox.setObjectName(_fromUtf8("jun_checkBox"))
        self.horizontalLayout_2.addWidget(self.jun_checkBox)
        self.jul_checkBox = QtGui.QCheckBox(self.horizontalGroupBox)
        self.jul_checkBox.setObjectName(_fromUtf8("jul_checkBox"))
        self.horizontalLayout_2.addWidget(self.jul_checkBox)
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.horizontalGroupBox)
        self.label_7 = QtGui.QLabel(self.verticalWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_7)
        self.groupBox_3 = QtGui.QGroupBox(self.verticalWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.aug_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.aug_checkBox.setGeometry(QtCore.QRect(10, 0, 54, 22))
        self.aug_checkBox.setObjectName(_fromUtf8("aug_checkBox"))
        self.sep_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.sep_checkBox.setGeometry(QtCore.QRect(70, 0, 53, 22))
        self.sep_checkBox.setObjectName(_fromUtf8("sep_checkBox"))
        self.oct_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.oct_checkBox.setGeometry(QtCore.QRect(140, 0, 52, 22))
        self.oct_checkBox.setObjectName(_fromUtf8("oct_checkBox"))
        self.nov_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.nov_checkBox.setGeometry(QtCore.QRect(200, 0, 55, 22))
        self.nov_checkBox.setObjectName(_fromUtf8("nov_checkBox"))
        self.dec_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.dec_checkBox.setGeometry(QtCore.QRect(260, 0, 54, 22))
        self.dec_checkBox.setObjectName(_fromUtf8("dec_checkBox"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.groupBox_3)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalFrame = QtGui.QFrame(JobEditDialog)
        self.verticalFrame.setGeometry(QtCore.QRect(0, 368, 511, 45))
        self.verticalFrame.setObjectName(_fromUtf8("verticalFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.verticalFrame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cancel_pushButton = QtGui.QPushButton(self.verticalFrame)
        self.cancel_pushButton.setObjectName(_fromUtf8("cancel_pushButton"))
        self.horizontalLayout.addWidget(self.cancel_pushButton)
        self.save_pushButton = QtGui.QPushButton(self.verticalFrame)
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.horizontalLayout.addWidget(self.save_pushButton)

        self.retranslateUi(JobEditDialog)
        QtCore.QObject.connect(self.cancel_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), JobEditDialog.reject)
        QtCore.QObject.connect(self.save_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), JobEditDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(JobEditDialog)

    def retranslateUi(self, JobEditDialog):
        JobEditDialog.setWindowTitle(_translate("JobEditDialog", "Job Editor", None))
        self.label.setText(_translate("JobEditDialog", "Comment", None))
        self.label_2.setText(_translate("JobEditDialog", "Command", None))
        self.enable_job_checkBox.setText(_translate("JobEditDialog", "Enable", None))
        self.label_4.setText(_translate("JobEditDialog", "Runtime", None))
        self.label_3.setText(_translate("JobEditDialog", "Time", None))
        self.label_5.setText(_translate("JobEditDialog", "Days", None))
        self.day_checkBox_1.setText(_translate("JobEditDialog", "1", None))
        self.day_checkBox_2.setText(_translate("JobEditDialog", "2", None))
        self.day_checkBox_3.setText(_translate("JobEditDialog", "3", None))
        self.day_checkBox_4.setText(_translate("JobEditDialog", "4", None))
        self.day_checkBox_5.setText(_translate("JobEditDialog", "5", None))
        self.day_checkBox_6.setText(_translate("JobEditDialog", "6", None))
        self.day_checkBox_7.setText(_translate("JobEditDialog", "7", None))
        self.label_6.setText(_translate("JobEditDialog", "Dow", None))
        self.sun_checkBox.setText(_translate("JobEditDialog", "SUN", None))
        self.mon_checkBox.setText(_translate("JobEditDialog", "MON", None))
        self.tue_checkBox.setText(_translate("JobEditDialog", "TUE", None))
        self.wed_checkBox.setText(_translate("JobEditDialog", "WED", None))
        self.thr_checkBox.setText(_translate("JobEditDialog", "THR", None))
        self.fri_checkBox.setText(_translate("JobEditDialog", "FRI", None))
        self.sat_checkBox.setText(_translate("JobEditDialog", "SAT", None))
        self.jan_checkBox.setText(_translate("JobEditDialog", "Jan", None))
        self.feb_checkBox.setText(_translate("JobEditDialog", "Feb", None))
        self.mar_checkBox.setText(_translate("JobEditDialog", "Mar", None))
        self.apr_checkBox.setText(_translate("JobEditDialog", "Apr", None))
        self.may_checkBox.setText(_translate("JobEditDialog", "May", None))
        self.jun_checkBox.setText(_translate("JobEditDialog", "Jun", None))
        self.jul_checkBox.setText(_translate("JobEditDialog", "Jul", None))
        self.label_7.setText(_translate("JobEditDialog", "Month", None))
        self.aug_checkBox.setText(_translate("JobEditDialog", "Aug", None))
        self.sep_checkBox.setText(_translate("JobEditDialog", "Sep", None))
        self.oct_checkBox.setText(_translate("JobEditDialog", "Oct", None))
        self.nov_checkBox.setText(_translate("JobEditDialog", "Nov", None))
        self.dec_checkBox.setText(_translate("JobEditDialog", "Dec", None))
        self.cancel_pushButton.setText(_translate("JobEditDialog", "Quit", None))
        self.save_pushButton.setText(_translate("JobEditDialog", "Save", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    JobEditDialog = QtGui.QDialog()
    ui = Ui_JobEditDialog()
    ui.setupUi(JobEditDialog)
    JobEditDialog.show()
    sys.exit(app.exec_())

